[project]
name = "rag-contextual"
version = "0.1.0"
description = "An agent is built by LangGraph and desgin based on RAG-Contextual."
authors = [
    {name = "BangNhatLe",email = "bangle37568@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = "3.11"
dependencies = [
    "langgraph (>=0.4.5,<0.5.0)",
    "jsonpickle (>=4.0.5,<5.0.0)",
    "duckduckgo-search (>=8.0.2,<9.0.0)",
    "langchain-community (>=0.3.24,<0.4.0)",
    "langchain-anthropic (>=0.3.13,<0.4.0)",
    "langchain-ollama (>=0.3.3,<0.4.0)",
    "ollama (>=0.4.8,<0.5.0)",
    "langchain-google-genai (>=2.1.4,<3.0.0)",
    "langchain-huggingface (>=0.2.0,<0.3.0)",
    "langchain-chroma (>=0.2.4,<0.3.0)",
    "nltk (>=3.9.1,<4.0.0)",
    "langgraph-cli (>=0.2.8,<0.2.10)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
